language: python
dist: trusty
sudo: false
python:
  - "2.7"
before_install:
    - sudo apt-get install -y libgdal-dev
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
