language: python
dist: bionic
services:
  - postgresql
sudo: true
python:
  - "3.6"
before_install:
  - sudo apt-get install --yes postgresql-10-postgis-2.4
before_script:
  - psql -c 'create database test_footprints;' -U postgres
  - psql -U postgres -c 'CREATE EXTENSION postgis;' -d test_footprints
script:
  - make travis
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
addons:
  postgresql: "10.11"
