language: python
dist: xenial
services:
  - postgresql
sudo: true
python:
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_footprints;' -U postgres
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
